#!/usr/bin/env python3
"""
Download audio and images for all Motifle songs.

Reads song_downloads.csv and image_downloads.csv generated by musicToSongs.py.
Skips already-downloaded files — safe to interrupt and re-run.

Audio output:  server/audio/<slug>.mp3    (≤128 kbps)
Image output:  server/images/<slug>.jpg

Usage:
  python3 download-audio.py              # download all missing audio + images
  python3 download-audio.py --audio      # audio only
  python3 download-audio.py --images     # images only
  python3 download-audio.py --retry      # retry slugs listed in failed.txt

Requirements:
  pip install yt-dlp requests
  ffmpeg on PATH (for mp3 conversion)
"""

import argparse
import csv
import subprocess
import sys
from pathlib import Path

try:
    import requests
except ImportError:
    requests = None

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

ROOT       = Path(__file__).parent
SONG_CSV   = ROOT / 'song_downloads.csv'
IMAGE_CSV  = ROOT / 'image_downloads.csv'
AUDIO_DIR  = ROOT / 'server' / 'audio'
IMAGE_DIR  = ROOT / 'server' / 'images'
FAILED_LOG = ROOT / 'server' / 'failed.txt'

# ---------------------------------------------------------------------------
# Audio download via yt-dlp
# ---------------------------------------------------------------------------

def download_audio(slug: str, url: str) -> bool:
    cmd = [
        'yt-dlp',
        '--extract-audio',
        '--audio-format', 'mp3',
        '--audio-quality', '128K',
        '--no-playlist',
        '--min-sleep-interval', '1.6',
        '--max-sleep-interval', '4.3',
        '--output', str(AUDIO_DIR / f'{slug}.%(ext)s'),
        '--quiet',
        '--no-warnings',
        url,
    ]
    try:
        r = subprocess.run(cmd, capture_output=True, text=True, timeout=300)
        if r.returncode == 0:
            return True
        err = (r.stderr or '').strip()
        print(f'    error: {err[-300:] or "unknown"}', file=sys.stderr)
        return False
    except subprocess.TimeoutExpired:
        print('    error: timed out', file=sys.stderr)
        return False
    except FileNotFoundError:
        print('yt-dlp not found. Install with: pip install yt-dlp', file=sys.stderr)
        sys.exit(1)


# ---------------------------------------------------------------------------
# Image download via requests
# ---------------------------------------------------------------------------

def cover_url(track_url: str) -> str:
    """Derive the album cover URL from a per-track image URL."""
    # .../album-art/{album}/{slug}.small.jpg → .../album-art/{album}/cover.small.jpg
    parts = track_url.rsplit('/', 1)
    return parts[0] + '/cover.small.jpg'


def download_image(slug: str, url: str) -> bool:
    if requests is None:
        print('requests not installed. Run: pip install requests', file=sys.stderr)
        sys.exit(1)
    urls_to_try = [url]
    fallback = cover_url(url)
    if fallback != url:
        urls_to_try.append(fallback)
    try:
        for attempt_url in urls_to_try:
            r = requests.get(attempt_url, timeout=30, headers={'User-Agent': 'motifle-bot/1.0'})
            if r.status_code == 200:
                (IMAGE_DIR / f'{slug}.jpg').write_bytes(r.content)
                return True
        print(f'    error: HTTP {r.status_code} (tried track + cover)', file=sys.stderr)
        return False
    except Exception as e:
        print(f'    error: {e}', file=sys.stderr)
        return False


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument('--audio',  action='store_true', help='Download audio only')
    parser.add_argument('--images', action='store_true', help='Download images only')
    parser.add_argument('--retry',  action='store_true', help='Retry slugs in failed.txt')
    args = parser.parse_args()

    do_audio  = not args.images  # default: both; --images disables audio
    do_images = not args.audio   # default: both; --audio disables images

    AUDIO_DIR.mkdir(parents=True, exist_ok=True)
    IMAGE_DIR.mkdir(parents=True, exist_ok=True)

    def load_csv(path):
        if not path.exists():
            print(f'Missing {path.name} — run musicToSongs.py first.', file=sys.stderr)
            sys.exit(1)
        with open(path, newline='', encoding='utf8') as f:
            return list(csv.DictReader(f))

    audio_rows = load_csv(SONG_CSV)  if do_audio  else []
    image_rows = load_csv(IMAGE_CSV) if do_images else []

    if args.retry:
        if not FAILED_LOG.exists():
            print('No failed.txt — nothing to retry.')
            return
        retry_slugs = set(FAILED_LOG.read_text().splitlines())
        audio_rows = [r for r in audio_rows if r['slug'] in retry_slugs]
        image_rows = [r for r in image_rows if r['slug'] in retry_slugs]
        print(f'Retrying {max(len(audio_rows), len(image_rows))} slugs from failed.txt')

    failed = []

    # ---- Audio ----
    if do_audio and audio_rows:
        total = len(audio_rows)
        n_done = n_skip = n_fail = 0
        print(f'\nAudio: {total} songs → {AUDIO_DIR}')
        for i, row in enumerate(audio_rows, 1):
            slug, url, source = row['slug'], row['url'], row['source']
            out = AUDIO_DIR / f'{slug}.mp3'
            if out.exists():
                n_skip += 1
                continue
            print(f'[{i:4}/{total}] {slug}  ({source})')
            if download_audio(slug, url):
                n_done += 1
            else:
                print(f'         FAIL  {slug}')
                n_fail += 1
                if slug not in failed:
                    failed.append(slug)
        print(f'Audio:  downloaded {n_done}  skipped {n_skip}  failed {n_fail}')

    # ---- Images ----
    if do_images and image_rows:
        total = len(image_rows)
        n_done = n_skip = n_fail = 0
        print(f'\nImages: {total} songs → {IMAGE_DIR}')
        for i, row in enumerate(image_rows, 1):
            slug, url = row['slug'], row['url']
            out = IMAGE_DIR / f'{slug}.jpg'
            if out.exists():
                n_skip += 1
                continue
            print(f'[{i:4}/{total}] {slug}')
            if download_image(slug, url):
                n_done += 1
            else:
                print(f'         FAIL  {slug}')
                n_fail += 1
                if slug not in failed:
                    failed.append(slug)
        print(f'Images: downloaded {n_done}  skipped {n_skip}  failed {n_fail}')

    if failed:
        FAILED_LOG.write_text('\n'.join(failed))
        print(f'\nFailed slugs → {FAILED_LOG}')
        print('Re-run with --retry to attempt them again.')
    elif FAILED_LOG.exists():
        FAILED_LOG.unlink()


if __name__ == '__main__':
    main()
